"""Seed data for Sheldon — cocktails, ingredients, clash rules, flavour profiles."""

# Ingredient knowledge base — flavour profiles & basic chemistry tags
INGREDIENTS = [
    # Spirits
    {"name": "Vodka", "category": "spirit", "abv": 40, "flavor_profile": ["neutral", "clean"], "notes": "Blank canvas. Lets other flavours shine."},
    {"name": "London Dry Gin", "category": "spirit", "abv": 40, "flavor_profile": ["juniper", "citrus", "herbal", "piney"], "notes": "Classic G&T base. Strong juniper backbone."},
    {"name": "Old Tom Gin", "category": "spirit", "abv": 40, "flavor_profile": ["juniper", "sweet", "malty"], "notes": "Slightly sweet, historical style. Tom Collins."},
    {"name": "Tequila Blanco", "category": "spirit", "abv": 40, "flavor_profile": ["agave", "vegetal", "peppery", "citrus"], "notes": "Bright, grassy. Margaritas, palomas."},
    {"name": "Tequila Reposado", "category": "spirit", "abv": 40, "flavor_profile": ["agave", "oak", "vanilla", "caramel"], "notes": "Aged 2-12 months. Smoother sipping."},
    {"name": "Mezcal", "category": "spirit", "abv": 42, "flavor_profile": ["smoky", "agave", "earthy", "leather"], "notes": "Smoke comes from underground roasting. Mexican Last Word, anyone?"},
    {"name": "White Rum", "category": "spirit", "abv": 40, "flavor_profile": ["sugarcane", "light", "vanilla", "tropical"], "notes": "Daiquiri, Mojito. Clean cane base."},
    {"name": "Aged Rum", "category": "spirit", "abv": 40, "flavor_profile": ["caramel", "vanilla", "oak", "spice"], "notes": "Sip it or build tikis. Mai Tai backbone."},
    {"name": "Dark Rum", "category": "spirit", "abv": 40, "flavor_profile": ["molasses", "burnt sugar", "spice"], "notes": "Heavy, sweet. Dark & Stormy."},
    {"name": "Bourbon", "category": "spirit", "abv": 45, "flavor_profile": ["vanilla", "caramel", "oak", "corn", "sweet"], "notes": "Min. 51% corn. Old Fashioned, Manhattan."},
    {"name": "Rye Whiskey", "category": "spirit", "abv": 45, "flavor_profile": ["spicy", "peppery", "dry", "grain"], "notes": "Spicy backbone. Sazerac, Manhattan (purists' choice)."},
    {"name": "Scotch (Blended)", "category": "spirit", "abv": 40, "flavor_profile": ["malty", "smoky", "honey"], "notes": "Versatile for highballs."},
    {"name": "Scotch (Islay/Peated)", "category": "spirit", "abv": 43, "flavor_profile": ["smoky", "peaty", "medicinal", "iodine"], "notes": "Penicillin loves a peated float."},
    {"name": "Irish Whiskey", "category": "spirit", "abv": 40, "flavor_profile": ["smooth", "honey", "vanilla", "light"], "notes": "Triple distilled, easy drinking."},
    {"name": "Cognac VS", "category": "spirit", "abv": 40, "flavor_profile": ["fruit", "oak", "vanilla", "warm"], "notes": "Sidecars, Vieux Carrés."},
    {"name": "Brandy", "category": "spirit", "abv": 40, "flavor_profile": ["fruit", "oak", "warm"], "notes": "Grape spirit base."},
    {"name": "Pisco", "category": "spirit", "abv": 40, "flavor_profile": ["grape", "floral", "light"], "notes": "Pisco Sour."},

    # Liqueurs & modifiers
    {"name": "Sweet Vermouth", "category": "fortified wine", "abv": 16, "flavor_profile": ["herbal", "sweet", "bitter", "spice"], "notes": "Refrigerate after opening! Manhattan, Negroni."},
    {"name": "Dry Vermouth", "category": "fortified wine", "abv": 16, "flavor_profile": ["herbal", "dry", "floral"], "notes": "Refrigerate. Martini, 50/50."},
    {"name": "Campari", "category": "amaro", "abv": 25, "flavor_profile": ["bitter", "orange", "herbal"], "notes": "Negroni, Boulevardier, Americano."},
    {"name": "Aperol", "category": "aperitivo", "abv": 11, "flavor_profile": ["bitter", "orange", "rhubarb", "light"], "notes": "Lighter than Campari. Spritz king."},
    {"name": "Fernet-Branca", "category": "amaro", "abv": 39, "flavor_profile": ["bitter", "menthol", "herbal", "intense"], "notes": "Industry handshake. Hanky Panky."},
    {"name": "Cointreau", "category": "liqueur", "abv": 40, "flavor_profile": ["orange", "sweet", "clean"], "notes": "Premium triple sec. Margaritas, Sidecars."},
    {"name": "Grand Marnier", "category": "liqueur", "abv": 40, "flavor_profile": ["orange", "cognac", "rich"], "notes": "Cognac-based orange liqueur."},
    {"name": "Maraschino", "category": "liqueur", "abv": 32, "flavor_profile": ["cherry", "nutty", "funky"], "notes": "Aviation, Last Word, Hemingway Daiquiri."},
    {"name": "Green Chartreuse", "category": "liqueur", "abv": 55, "flavor_profile": ["herbal", "intense", "vegetal", "spicy"], "notes": "130 botanicals. Last Word, Bijou."},
    {"name": "Yellow Chartreuse", "category": "liqueur", "abv": 40, "flavor_profile": ["herbal", "honey", "milder"], "notes": "Softer than green."},
    {"name": "St-Germain (Elderflower)", "category": "liqueur", "abv": 20, "flavor_profile": ["floral", "elderflower", "lychee", "sweet"], "notes": "Bartender's ketchup — goes with everything."},
    {"name": "Crème de Cassis", "category": "liqueur", "abv": 15, "flavor_profile": ["blackcurrant", "sweet", "fruit"], "notes": "Kir, Kir Royale."},
    {"name": "Crème de Mûre", "category": "liqueur", "abv": 15, "flavor_profile": ["blackberry", "sweet"], "notes": "Bramble."},
    {"name": "Crème de Cacao", "category": "liqueur", "abv": 25, "flavor_profile": ["chocolate", "sweet"], "notes": "Brandy Alexander, Grasshopper."},
    {"name": "Coffee Liqueur (Kahlúa)", "category": "liqueur", "abv": 20, "flavor_profile": ["coffee", "sweet", "vanilla"], "notes": "Espresso Martini, White Russian."},
    {"name": "Amaretto", "category": "liqueur", "abv": 24, "flavor_profile": ["almond", "stone fruit", "sweet"], "notes": "Amaretto Sour, Godfather."},
    {"name": "Drambuie", "category": "liqueur", "abv": 40, "flavor_profile": ["honey", "herbal", "scotch"], "notes": "Rusty Nail."},
    {"name": "Baileys Irish Cream", "category": "cream liqueur", "abv": 17, "flavor_profile": ["cream", "whiskey", "chocolate", "sweet"], "notes": "DAIRY — will curdle with acid (citrus, wine, tonic). Mind the chemistry."},
    {"name": "Pernod / Absinthe", "category": "liqueur", "abv": 60, "flavor_profile": ["anise", "fennel", "herbal"], "notes": "Sazerac rinse. A few drops go a long way."},
    {"name": "Benedictine", "category": "liqueur", "abv": 40, "flavor_profile": ["herbal", "honey", "spice"], "notes": "Vieux Carré."},
    {"name": "Galliano", "category": "liqueur", "abv": 30, "flavor_profile": ["vanilla", "anise", "herbal"], "notes": "Harvey Wallbanger."},

    # Bitters
    {"name": "Angostura Bitters", "category": "bitters", "abv": 44, "flavor_profile": ["spice", "clove", "bitter"], "notes": "The OG. 2-3 dashes in most stirred drinks."},
    {"name": "Orange Bitters", "category": "bitters", "abv": 40, "flavor_profile": ["orange", "bitter", "warm"], "notes": "Martini, Old Fashioned (variant)."},
    {"name": "Peychaud's Bitters", "category": "bitters", "abv": 35, "flavor_profile": ["anise", "floral", "bitter"], "notes": "Mandatory in a Sazerac."},

    # Mixers / juices / syrups
    {"name": "Lime Juice", "category": "juice", "abv": 0, "flavor_profile": ["citrus", "tart", "bright"], "notes": "Fresh only. Oxidises within hours."},
    {"name": "Lemon Juice", "category": "juice", "abv": 0, "flavor_profile": ["citrus", "tart", "fresh"], "notes": "Fresh only."},
    {"name": "Orange Juice", "category": "juice", "abv": 0, "flavor_profile": ["citrus", "sweet"], "notes": "Fresh for service."},
    {"name": "Grapefruit Juice", "category": "juice", "abv": 0, "flavor_profile": ["citrus", "bitter", "tart"], "notes": "Paloma."},
    {"name": "Pineapple Juice", "category": "juice", "abv": 0, "flavor_profile": ["tropical", "sweet", "tart"], "notes": "Shakes to a froth — pineapple-syrup foam."},
    {"name": "Cranberry Juice", "category": "juice", "abv": 0, "flavor_profile": ["tart", "fruit"], "notes": "Cosmo, Cape Codder."},
    {"name": "Simple Syrup (1:1)", "category": "syrup", "abv": 0, "flavor_profile": ["sweet"], "notes": "Equal parts sugar/water."},
    {"name": "Rich Simple (2:1)", "category": "syrup", "abv": 0, "flavor_profile": ["sweet", "thick"], "notes": "2:1 sugar:water. Old Fashioned weapon of choice."},
    {"name": "Demerara Syrup", "category": "syrup", "abv": 0, "flavor_profile": ["sweet", "molasses", "caramel"], "notes": "Tiki, aged rum drinks."},
    {"name": "Honey Syrup", "category": "syrup", "abv": 0, "flavor_profile": ["floral", "sweet"], "notes": "3:1 honey:water. Bee's Knees, Penicillin."},
    {"name": "Agave Syrup", "category": "syrup", "abv": 0, "flavor_profile": ["sweet", "vegetal"], "notes": "Pairs with tequila/mezcal."},
    {"name": "Grenadine (real)", "category": "syrup", "abv": 0, "flavor_profile": ["pomegranate", "sweet"], "notes": "Real is pomegranate, not red dye."},
    {"name": "Orgeat", "category": "syrup", "abv": 0, "flavor_profile": ["almond", "nutty", "sweet", "floral"], "notes": "Mai Tai, Japanese Cocktail."},
    {"name": "Egg White", "category": "modifier", "abv": 0, "flavor_profile": ["neutral"], "notes": "Silky texture, foam. Dry shake first!"},
    {"name": "Heavy Cream", "category": "dairy", "abv": 0, "flavor_profile": ["cream", "rich"], "notes": "WILL CURDLE with citrus/acidic wines."},
    {"name": "Coconut Cream", "category": "dairy alt", "abv": 0, "flavor_profile": ["tropical", "creamy", "sweet"], "notes": "Piña Colada."},
    {"name": "Soda Water", "category": "mixer", "abv": 0, "flavor_profile": ["neutral", "fizz"], "notes": "Length, lift, dilution."},
    {"name": "Tonic Water", "category": "mixer", "abv": 0, "flavor_profile": ["bitter", "quinine", "sweet"], "notes": "G&T. Quinine can clash with cream."},
    {"name": "Ginger Beer", "category": "mixer", "abv": 0, "flavor_profile": ["spicy", "ginger", "sweet"], "notes": "Mules, Dark & Stormy."},
    {"name": "Champagne / Prosecco", "category": "wine", "abv": 12, "flavor_profile": ["fizzy", "dry", "yeasty"], "notes": "French 75, Spritz, Mimosa."},
]

# Clash / compatibility rules
CLASH_RULES = [
    {"a": "Baileys Irish Cream", "b": "Lime Juice", "severity": "fatal", "reason": "Dairy cream curdles immediately on contact with citric acid — turns lumpy and inedible."},
    {"a": "Baileys Irish Cream", "b": "Lemon Juice", "severity": "fatal", "reason": "Same as lime — citric acid curdles the cream."},
    {"a": "Baileys Irish Cream", "b": "Grapefruit Juice", "severity": "fatal", "reason": "Citric acid → curdles."},
    {"a": "Baileys Irish Cream", "b": "Tonic Water", "severity": "high", "reason": "Quinine + dairy = curdling and a chalky mouthfeel."},
    {"a": "Baileys Irish Cream", "b": "Champagne / Prosecco", "severity": "high", "reason": "Acidic wine + dairy curdles."},
    {"a": "Heavy Cream", "b": "Lime Juice", "severity": "fatal", "reason": "Acid + cream = curdle. Use coconut cream instead for tropical creamy citrus."},
    {"a": "Heavy Cream", "b": "Lemon Juice", "severity": "fatal", "reason": "Same — curdles."},
    {"a": "Heavy Cream", "b": "Champagne / Prosecco", "severity": "high", "reason": "Acidic sparkling wine curdles cream."},
    {"a": "Pernod / Absinthe", "b": "Cream", "severity": "medium", "reason": "Anise-louche can muddy a creamy drink. Use sparingly."},
    {"a": "Campari", "b": "Heavy Cream", "severity": "medium", "reason": "Bitter + cream is rarely pleasant. Doable but tricky."},
    {"a": "Mezcal", "b": "Crème de Cacao", "severity": "low", "reason": "Smoke vs chocolate can clash if proportions are off. Possible but careful."},
    {"a": "Tequila Blanco", "b": "Coffee Liqueur (Kahlúa)", "severity": "low", "reason": "Vegetal agave vs sweet coffee — unusual pairing, balance carefully."},
    {"a": "Fernet-Branca", "b": "Sweet liqueurs", "severity": "low", "reason": "Fernet's intense bitterness fights most sweet liqueurs. Use in small accents."},
    {"a": "London Dry Gin", "b": "Coffee Liqueur (Kahlúa)", "severity": "medium", "reason": "Pine/juniper vs coffee is a strange flavour battle."},
]

# Classic cocktail recipes
COCKTAILS = [
    {
        "name": "Old Fashioned",
        "category": "spirit-forward",
        "glassware": "Rocks",
        "garnish": "Orange peel (express oils)",
        "method": "Build & stir",
        "ingredients": [
            {"name": "Bourbon", "amount_ml": 60, "notes": "or Rye"},
            {"name": "Rich Simple (2:1)", "amount_ml": 5},
            {"name": "Angostura Bitters", "amount_ml": 1.5, "notes": "2-3 dashes"},
        ],
        "instructions": "Add all to mixing glass with ice. Stir 30s until well diluted. Strain over large rock. Express orange peel over and drop in.",
        "flavor_profile": ["sweet", "bitter", "warm", "spirit-forward"],
        "abv_estimate": 32,
        "tags": ["classic", "IBA", "stirred"],
    },
    {
        "name": "Manhattan",
        "category": "spirit-forward",
        "glassware": "Coupe",
        "garnish": "Brandied cherry",
        "method": "Stir",
        "ingredients": [
            {"name": "Rye Whiskey", "amount_ml": 60},
            {"name": "Sweet Vermouth", "amount_ml": 30},
            {"name": "Angostura Bitters", "amount_ml": 1.5, "notes": "2 dashes"},
        ],
        "instructions": "Stir over ice 30s. Strain into chilled coupe. Cherry garnish.",
        "flavor_profile": ["sweet", "spicy", "herbal", "spirit-forward"],
        "abv_estimate": 28,
        "tags": ["classic", "IBA", "stirred"],
    },
    {
        "name": "Negroni",
        "category": "bitter",
        "glassware": "Rocks",
        "garnish": "Orange wheel or peel",
        "method": "Build & stir",
        "ingredients": [
            {"name": "London Dry Gin", "amount_ml": 30},
            {"name": "Campari", "amount_ml": 30},
            {"name": "Sweet Vermouth", "amount_ml": 30},
        ],
        "instructions": "Build over ice in rocks glass. Stir briefly. Orange peel.",
        "flavor_profile": ["bitter", "herbal", "orange"],
        "abv_estimate": 24,
        "tags": ["classic", "IBA", "equal-parts"],
    },
    {
        "name": "Boulevardier",
        "category": "bitter",
        "glassware": "Rocks or coupe",
        "garnish": "Orange peel",
        "method": "Stir",
        "ingredients": [
            {"name": "Bourbon", "amount_ml": 45},
            {"name": "Campari", "amount_ml": 30},
            {"name": "Sweet Vermouth", "amount_ml": 30},
        ],
        "instructions": "Stir over ice. Strain over fresh rock or up. Orange peel.",
        "flavor_profile": ["bitter", "sweet", "warm"],
        "abv_estimate": 26,
        "tags": ["classic", "stirred"],
    },
    {
        "name": "Margarita",
        "category": "sour",
        "glassware": "Coupe or rocks",
        "garnish": "Half salt rim, lime wheel",
        "method": "Shake",
        "ingredients": [
            {"name": "Tequila Blanco", "amount_ml": 50},
            {"name": "Cointreau", "amount_ml": 20},
            {"name": "Lime Juice", "amount_ml": 25},
        ],
        "instructions": "Shake hard with ice 12s. Double strain. Optional half salt rim.",
        "flavor_profile": ["citrus", "agave", "sweet", "tart"],
        "abv_estimate": 22,
        "tags": ["classic", "IBA", "shaken", "citrus"],
    },
    {
        "name": "Tommy's Margarita",
        "category": "sour",
        "glassware": "Rocks",
        "garnish": "Lime wheel",
        "method": "Shake",
        "ingredients": [
            {"name": "Tequila Blanco", "amount_ml": 60},
            {"name": "Lime Juice", "amount_ml": 25},
            {"name": "Agave Syrup", "amount_ml": 15},
        ],
        "instructions": "Shake hard. Strain over fresh ice.",
        "flavor_profile": ["citrus", "agave", "clean"],
        "abv_estimate": 22,
        "tags": ["modern classic"],
    },
    {
        "name": "Daiquiri",
        "category": "sour",
        "glassware": "Coupe",
        "garnish": "Lime wheel",
        "method": "Shake",
        "ingredients": [
            {"name": "White Rum", "amount_ml": 60},
            {"name": "Lime Juice", "amount_ml": 25},
            {"name": "Simple Syrup (1:1)", "amount_ml": 15},
        ],
        "instructions": "Shake hard, double strain into chilled coupe.",
        "flavor_profile": ["citrus", "sweet", "clean"],
        "abv_estimate": 22,
        "tags": ["classic", "IBA", "shaken", "citrus"],
    },
    {
        "name": "Whiskey Sour",
        "category": "sour",
        "glassware": "Coupe or rocks",
        "garnish": "Cherry, optional orange",
        "method": "Shake (dry shake if using egg white)",
        "ingredients": [
            {"name": "Bourbon", "amount_ml": 60},
            {"name": "Lemon Juice", "amount_ml": 25},
            {"name": "Simple Syrup (1:1)", "amount_ml": 20},
            {"name": "Egg White", "amount_ml": 15, "notes": "optional"},
        ],
        "instructions": "Dry shake (no ice) 15s if using egg white, then shake with ice. Strain.",
        "flavor_profile": ["sweet", "sour", "warm"],
        "abv_estimate": 18,
        "tags": ["classic", "IBA"],
    },
    {
        "name": "Espresso Martini",
        "category": "after-dinner",
        "glassware": "Coupe",
        "garnish": "3 coffee beans",
        "method": "Shake (hard)",
        "ingredients": [
            {"name": "Vodka", "amount_ml": 50},
            {"name": "Coffee Liqueur (Kahlúa)", "amount_ml": 20},
            {"name": "Simple Syrup (1:1)", "amount_ml": 10},
            {"name": "Espresso", "amount_ml": 30, "notes": "fresh, hot or cold-brew concentrate"},
        ],
        "instructions": "Shake VERY hard with ice for that crema-like foam. Double strain. Three beans on top.",
        "flavor_profile": ["coffee", "sweet", "rich"],
        "abv_estimate": 22,
        "tags": ["modern classic", "shaken"],
    },
    {
        "name": "Mojito",
        "category": "highball",
        "glassware": "Highball",
        "garnish": "Mint sprig, lime wedge",
        "method": "Build",
        "ingredients": [
            {"name": "White Rum", "amount_ml": 50},
            {"name": "Lime Juice", "amount_ml": 25},
            {"name": "Simple Syrup (1:1)", "amount_ml": 15},
            {"name": "Mint leaves", "amount_ml": 0, "notes": "8-10 leaves, gently slapped (NOT muddled to mush)"},
            {"name": "Soda Water", "amount_ml": 60, "notes": "top"},
        ],
        "instructions": "Gently press mint (don't shred it). Add rum, lime, syrup, ice. Top soda. Stir lightly.",
        "flavor_profile": ["mint", "citrus", "refreshing"],
        "abv_estimate": 12,
        "tags": ["classic", "IBA", "long"],
    },
    {
        "name": "Aperol Spritz",
        "category": "aperitivo",
        "glassware": "Wine glass",
        "garnish": "Orange slice",
        "method": "Build",
        "ingredients": [
            {"name": "Aperol", "amount_ml": 60},
            {"name": "Champagne / Prosecco", "amount_ml": 90},
            {"name": "Soda Water", "amount_ml": 30, "notes": "splash"},
        ],
        "instructions": "Fill wine glass with ice. Prosecco first (preserves bubbles), then Aperol, splash soda. Orange.",
        "flavor_profile": ["bitter", "orange", "fizzy", "light"],
        "abv_estimate": 11,
        "tags": ["classic", "IBA", "low-abv", "aperitif"],
    },
    {
        "name": "Penicillin",
        "category": "sour",
        "glassware": "Rocks",
        "garnish": "Candied ginger, optional peated float",
        "method": "Shake + float",
        "ingredients": [
            {"name": "Scotch (Blended)", "amount_ml": 60},
            {"name": "Lemon Juice", "amount_ml": 22.5},
            {"name": "Honey Syrup", "amount_ml": 22.5, "notes": "ginger-infused honey is the move"},
            {"name": "Scotch (Islay/Peated)", "amount_ml": 7.5, "notes": "float on top"},
        ],
        "instructions": "Shake first three with ice. Strain over fresh rock. Gently float peated scotch via spoon.",
        "flavor_profile": ["smoky", "honey", "ginger", "citrus"],
        "abv_estimate": 22,
        "tags": ["modern classic"],
    },
    {
        "name": "Paper Plane",
        "category": "sour",
        "glassware": "Coupe",
        "garnish": "None (or paper plane)",
        "method": "Shake",
        "ingredients": [
            {"name": "Bourbon", "amount_ml": 22.5},
            {"name": "Aperol", "amount_ml": 22.5},
            {"name": "Amaro Nonino", "amount_ml": 22.5, "notes": "or another medium-bitter amaro"},
            {"name": "Lemon Juice", "amount_ml": 22.5},
        ],
        "instructions": "Equal parts shake. Double strain.",
        "flavor_profile": ["bitter", "citrus", "herbal"],
        "abv_estimate": 18,
        "tags": ["modern classic", "equal-parts"],
    },
    {
        "name": "French 75",
        "category": "champagne",
        "glassware": "Flute",
        "garnish": "Lemon twist",
        "method": "Shake + top",
        "ingredients": [
            {"name": "London Dry Gin", "amount_ml": 30},
            {"name": "Lemon Juice", "amount_ml": 15},
            {"name": "Simple Syrup (1:1)", "amount_ml": 10},
            {"name": "Champagne / Prosecco", "amount_ml": 60, "notes": "top"},
        ],
        "instructions": "Shake first three. Strain into flute. Top with bubbles. Lemon twist.",
        "flavor_profile": ["citrus", "dry", "fizzy"],
        "abv_estimate": 16,
        "tags": ["classic", "IBA"],
    },
    {
        "name": "Last Word",
        "category": "sour",
        "glassware": "Coupe",
        "garnish": "Brandied cherry",
        "method": "Shake",
        "ingredients": [
            {"name": "London Dry Gin", "amount_ml": 22.5},
            {"name": "Green Chartreuse", "amount_ml": 22.5},
            {"name": "Maraschino", "amount_ml": 22.5},
            {"name": "Lime Juice", "amount_ml": 22.5},
        ],
        "instructions": "Shake equal parts. Double strain.",
        "flavor_profile": ["herbal", "citrus", "complex"],
        "abv_estimate": 24,
        "tags": ["classic", "equal-parts"],
    },
    {
        "name": "Aviation",
        "category": "sour",
        "glassware": "Coupe",
        "garnish": "Brandied cherry",
        "method": "Shake",
        "ingredients": [
            {"name": "London Dry Gin", "amount_ml": 45},
            {"name": "Maraschino", "amount_ml": 15},
            {"name": "Crème de Violette", "amount_ml": 7.5},
            {"name": "Lemon Juice", "amount_ml": 22.5},
        ],
        "instructions": "Shake. Double strain. Pale violet hue.",
        "flavor_profile": ["floral", "citrus", "complex"],
        "abv_estimate": 22,
        "tags": ["classic", "IBA"],
    },
    {
        "name": "Cosmopolitan",
        "category": "sour",
        "glassware": "Coupe",
        "garnish": "Lime wheel or flamed orange",
        "method": "Shake",
        "ingredients": [
            {"name": "Citrus Vodka", "amount_ml": 45, "notes": "or plain vodka"},
            {"name": "Cointreau", "amount_ml": 15},
            {"name": "Lime Juice", "amount_ml": 15},
            {"name": "Cranberry Juice", "amount_ml": 30},
        ],
        "instructions": "Shake hard. Double strain.",
        "flavor_profile": ["tart", "fruity", "citrus"],
        "abv_estimate": 22,
        "tags": ["classic", "IBA"],
    },
    {
        "name": "Gimlet",
        "category": "sour",
        "glassware": "Coupe",
        "garnish": "Lime wheel",
        "method": "Shake",
        "ingredients": [
            {"name": "London Dry Gin", "amount_ml": 60},
            {"name": "Lime Juice", "amount_ml": 22.5},
            {"name": "Simple Syrup (1:1)", "amount_ml": 15},
        ],
        "instructions": "Shake. Strain into coupe.",
        "flavor_profile": ["citrus", "herbal", "dry"],
        "abv_estimate": 24,
        "tags": ["classic"],
    },
    {
        "name": "Sazerac",
        "category": "spirit-forward",
        "glassware": "Rocks (chilled, no ice)",
        "garnish": "Lemon peel (express, discard)",
        "method": "Stir + rinse",
        "ingredients": [
            {"name": "Rye Whiskey", "amount_ml": 60, "notes": "or cognac"},
            {"name": "Pernod / Absinthe", "amount_ml": 5, "notes": "RINSE — discard excess"},
            {"name": "Demerara Syrup", "amount_ml": 5},
            {"name": "Peychaud's Bitters", "amount_ml": 1.5, "notes": "3 dashes"},
        ],
        "instructions": "Rinse chilled rocks glass with absinthe (discard). Stir rye, syrup, bitters over ice. Strain into prepared glass (no ice). Lemon peel, discard.",
        "flavor_profile": ["spicy", "anise", "complex", "spirit-forward"],
        "abv_estimate": 38,
        "tags": ["classic", "IBA", "stirred"],
    },
    {
        "name": "Vesper",
        "category": "spirit-forward",
        "glassware": "Coupe",
        "garnish": "Lemon peel",
        "method": "Shake (per Bond) or stir",
        "ingredients": [
            {"name": "London Dry Gin", "amount_ml": 60},
            {"name": "Vodka", "amount_ml": 20},
            {"name": "Lillet Blanc", "amount_ml": 10},
        ],
        "instructions": "Shake or stir until very cold. Strain into chilled coupe. Lemon peel.",
        "flavor_profile": ["dry", "clean", "spirit-forward"],
        "abv_estimate": 32,
        "tags": ["classic", "IBA"],
    },
    {
        "name": "Dark & Stormy",
        "category": "highball",
        "glassware": "Highball",
        "garnish": "Lime wedge",
        "method": "Build",
        "ingredients": [
            {"name": "Dark Rum", "amount_ml": 60, "notes": "Gosling's traditionally"},
            {"name": "Ginger Beer", "amount_ml": 120},
            {"name": "Lime Juice", "amount_ml": 15, "notes": "optional"},
        ],
        "instructions": "Build over ice in highball. Float rum over ginger beer for the 'stormy' look.",
        "flavor_profile": ["spicy", "molasses", "citrus"],
        "abv_estimate": 11,
        "tags": ["classic", "long"],
    },
    {
        "name": "Bramble",
        "category": "sour",
        "glassware": "Rocks (crushed ice)",
        "garnish": "Blackberry, lemon wedge",
        "method": "Build + drizzle",
        "ingredients": [
            {"name": "London Dry Gin", "amount_ml": 50},
            {"name": "Lemon Juice", "amount_ml": 25},
            {"name": "Simple Syrup (1:1)", "amount_ml": 12.5},
            {"name": "Crème de Mûre", "amount_ml": 15, "notes": "drizzle"},
        ],
        "instructions": "Shake first three. Strain over crushed ice. Drizzle mûre over the top for that bleeding-in look.",
        "flavor_profile": ["citrus", "berry", "fruity"],
        "abv_estimate": 18,
        "tags": ["modern classic", "IBA"],
    },
]
