"""Seed data for Sheldon — cocktails, ingredients, clash rules, flavour profiles."""

# Ingredient knowledge base — flavour profiles & basic chemistry tags
INGREDIENTS = [
    # Spirits
    {"name": "Vodka", "category": "spirit", "abv": 40, "flavor_profile": ["neutral", "clean"], "notes": "Blank canvas. Lets other flavours shine."},
    {"name": "London Dry Gin", "category": "spirit", "abv": 40, "flavor_profile": ["juniper", "citrus", "herbal", "piney"], "notes": "Classic G&T base. Strong juniper backbone."},
    {"name": "Old Tom Gin", "category": "spirit", "abv": 40, "flavor_profile": ["juniper", "sweet", "malty"], "notes": "Slightly sweet, historical style. Tom Collins."},
    {"name": "Tequila Blanco", "category": "spirit", "abv": 40, "flavor_profile": ["agave", "vegetal", "peppery", "citrus"], "notes": "Bright, grassy. Margaritas, palomas."},
    {"name": "Tequila Reposado", "category": "spirit", "abv": 40, "flavor_profile": ["agave", "oak", "vanilla", "caramel"], "notes": "Aged 2-12 months. Smoother sipping."},
    {"name": "Mezcal", "category": "spirit", "abv": 42, "flavor_profile": ["smoky", "agave", "earthy", "leather"], "notes": "Smoke comes from underground roasting. Mexican Last Word, anyone?"},
    {"name": "White Rum", "category": "spirit", "abv": 40, "flavor_profile": ["sugarcane", "light", "vanilla", "tropical"], "notes": "Daiquiri, Mojito. Clean cane base."},
    {"name": "Aged Rum", "category": "spirit", "abv": 40, "flavor_profile": ["caramel", "vanilla", "oak", "spice"], "notes": "Sip it or build tikis. Mai Tai backbone."},
    {"name": "Dark Rum", "category": "spirit", "abv": 40, "flavor_profile": ["molasses", "burnt sugar", "spice"], "notes": "Heavy, sweet. Dark & Stormy."},
    {"name": "Bourbon", "category": "spirit", "abv": 45, "flavor_profile": ["vanilla", "caramel", "oak", "corn", "sweet"], "notes": "Min. 51% corn. Old Fashioned, Manhattan."},
    {"name": "Rye Whiskey", "category": "spirit", "abv": 45, "flavor_profile": ["spicy", "peppery", "dry", "grain"], "notes": "Spicy backbone. Sazerac, Manhattan (purists' choice)."},
    {"name": "Scotch (Blended)", "category": "spirit", "abv": 40, "flavor_profile": ["malty", "smoky", "honey"], "notes": "Versatile for highballs."},
    {"name": "Scotch (Islay/Peated)", "category": "spirit", "abv": 43, "flavor_profile": ["smoky", "peaty", "medicinal", "iodine"], "notes": "Penicillin loves a peated float."},
    {"name": "Irish Whiskey", "category": "spirit", "abv": 40, "flavor_profile": ["smooth", "honey", "vanilla", "light"], "notes": "Triple distilled, easy drinking."},
    {"name": "Cognac VS", "category": "spirit", "abv": 40, "flavor_profile": ["fruit", "oak", "vanilla", "warm"], "notes": "Sidecars, Vieux Carrés."},
    {"name": "Brandy", "category": "spirit", "abv": 40, "flavor_profile": ["fruit", "oak", "warm"], "notes": "Grape spirit base."},
    {"name": "Pisco", "category": "spirit", "abv": 40, "flavor_profile": ["grape", "floral", "light"], "notes": "Pisco Sour."},

    # Liqueurs & modifiers
    {"name": "Sweet Vermouth", "category": "fortified wine", "abv": 16, "flavor_profile": ["herbal", "sweet", "bitter", "spice"], "notes": "Refrigerate after opening! Manhattan, Negroni."},
    {"name": "Dry Vermouth", "category": "fortified wine", "abv": 16, "flavor_profile": ["herbal", "dry", "floral"], "notes": "Refrigerate. Martini, 50/50."},
    {"name": "Campari", "category": "amaro", "abv": 25, "flavor_profile": ["bitter", "orange", "herbal"], "notes": "Negroni, Boulevardier, Americano."},
    {"name": "Aperol", "category": "aperitivo", "abv": 11, "flavor_profile": ["bitter", "orange", "rhubarb", "light"], "notes": "Lighter than Campari. Spritz king."},
    {"name": "Fernet-Branca", "category": "amaro", "abv": 39, "flavor_profile": ["bitter", "menthol", "herbal", "intense"], "notes": "Industry handshake. Hanky Panky."},
    {"name": "Cointreau", "category": "liqueur", "abv": 40, "flavor_profile": ["orange", "sweet", "clean"], "notes": "Premium triple sec. Margaritas, Sidecars."},
    {"name": "Grand Marnier", "category": "liqueur", "abv": 40, "flavor_profile": ["orange", "cognac", "rich"], "notes": "Cognac-based orange liqueur."},
    {"name": "Maraschino", "category": "liqueur", "abv": 32, "flavor_profile": ["cherry", "nutty", "funky"], "notes": "Aviation, Last Word, Hemingway Daiquiri."},
    {"name": "Green Chartreuse", "category": "liqueur", "abv": 55, "flavor_profile": ["herbal", "intense", "vegetal", "spicy"], "notes": "130 botanicals. Last Word, Bijou."},
    {"name": "Yellow Chartreuse", "category": "liqueur", "abv": 40, "flavor_profile": ["herbal", "honey", "milder"], "notes": "Softer than green."},
    {"name": "St-Germain (Elderflower)", "category": "liqueur", "abv": 20, "flavor_profile": ["floral", "elderflower", "lychee", "sweet"], "notes": "Bartender's ketchup — goes with everything."},
    {"name": "Crème de Cassis", "category": "liqueur", "abv": 15, "flavor_profile": ["blackcurrant", "sweet", "fruit"], "notes": "Kir, Kir Royale."},
    {"name": "Crème de Mûre", "category": "liqueur", "abv": 15, "flavor_profile": ["blackberry", "sweet"], "notes": "Bramble."},
    {"name": "Crème de Cacao", "category": "liqueur", "abv": 25, "flavor_profile": ["chocolate", "sweet"], "notes": "Brandy Alexander, Grasshopper."},
    {"name": "Coffee Liqueur (Kahlúa)", "category": "liqueur", "abv": 20, "flavor_profile": ["coffee", "sweet", "vanilla"], "notes": "Espresso Martini, White Russian."},
    {"name": "Amaretto", "category": "liqueur", "abv": 24, "flavor_profile": ["almond", "stone fruit", "sweet"], "notes": "Amaretto Sour, Godfather."},
    {"name": "Drambuie", "category": "liqueur", "abv": 40, "flavor_profile": ["honey", "herbal", "scotch"], "notes": "Rusty Nail."},
    {"name": "Baileys Irish Cream", "category": "cream liqueur", "abv": 17, "flavor_profile": ["cream", "whiskey", "chocolate", "sweet"], "notes": "DAIRY — will curdle with acid (citrus, wine, tonic). Mind the chemistry."},
    {"name": "Pernod / Absinthe", "category": "liqueur", "abv": 60, "flavor_profile": ["anise", "fennel", "herbal"], "notes": "Sazerac rinse. A few drops go a long way."},
    {"name": "Benedictine", "category": "liqueur", "abv": 40, "flavor_profile": ["herbal", "honey", "spice"], "notes": "Vieux Carré."},
    {"name": "Galliano", "category": "liqueur", "abv": 30, "flavor_profile": ["vanilla", "anise", "herbal"], "notes": "Harvey Wallbanger."},
    {"name": "Lillet Blanc", "category": "fortified wine", "abv": 17, "flavor_profile": ["floral", "honey", "citrus", "light"], "notes": "Quinquina. Vesper, Corpse Reviver #2."},
    {"name": "Cocchi Americano", "category": "fortified wine", "abv": 16, "flavor_profile": ["bitter", "citrus", "honey", "quinine"], "notes": "Closest modern stand-in for Kina Lillet."},
    {"name": "Punt e Mes", "category": "fortified wine", "abv": 16, "flavor_profile": ["bitter", "sweet", "herbal"], "notes": "Bitter sweet vermouth — Manhattan with edge."},
    {"name": "Carpano Antica Formula", "category": "fortified wine", "abv": 16, "flavor_profile": ["rich", "vanilla", "herbal", "sweet"], "notes": "Premium sweet vermouth — use slightly less."},
    {"name": "Suze", "category": "amaro", "abv": 20, "flavor_profile": ["bitter", "gentian", "earthy"], "notes": "Gentian root. White Negroni base."},
    {"name": "Gran Classico", "category": "amaro", "abv": 28, "flavor_profile": ["bitter", "herbal", "citrus"], "notes": "Drier alternative to Campari."},
    {"name": "Amaro Nonino", "category": "amaro", "abv": 35, "flavor_profile": ["bitter", "sweet", "grappa", "herbal"], "notes": "Paper Plane essential. Medium bitter."},
    {"name": "Cynar", "category": "amaro", "abv": 16.5, "flavor_profile": ["bitter", "vegetal", "artichoke"], "notes": "Artichoke amaro. Cynar Spritz."},
    {"name": "Cachaça", "category": "spirit", "abv": 40, "flavor_profile": ["sugarcane", "grassy", "funky", "vegetal"], "notes": "Brazilian cane spirit. Caipirinha only, really."},
    {"name": "Crème de Violette", "category": "liqueur", "abv": 20, "flavor_profile": ["floral", "violet", "sweet"], "notes": "Aviation. A few ml turns drinks pale lavender."},
    {"name": "Falernum", "category": "liqueur", "abv": 11, "flavor_profile": ["lime", "ginger", "clove", "almond"], "notes": "Tiki essential. John D. Taylor's is the standard."},
    {"name": "Orange Curaçao", "category": "liqueur", "abv": 30, "flavor_profile": ["orange", "sweet", "warm"], "notes": "Mai Tai. Pierre Ferrand is the go."},
    {"name": "Aquafaba", "category": "modifier", "abv": 0, "flavor_profile": ["neutral"], "notes": "Vegan egg-white sub. Chickpea brine. Same dry-shake."},
    {"name": "Mint Leaves", "category": "herb", "abv": 0, "flavor_profile": ["mint", "herbal", "fresh"], "notes": "Slap, don't muddle to pulp. Mojitos, juleps."},
    {"name": "Espresso", "category": "modifier", "abv": 0, "flavor_profile": ["coffee", "bitter", "rich"], "notes": "Fresh, hot. Espresso Martini."},

    # Bitters
    {"name": "Angostura Bitters", "category": "bitters", "abv": 44, "flavor_profile": ["spice", "clove", "bitter"], "notes": "The OG. 2-3 dashes in most stirred drinks."},
    {"name": "Orange Bitters", "category": "bitters", "abv": 40, "flavor_profile": ["orange", "bitter", "warm"], "notes": "Martini, Old Fashioned (variant)."},
    {"name": "Peychaud's Bitters", "category": "bitters", "abv": 35, "flavor_profile": ["anise", "floral", "bitter"], "notes": "Mandatory in a Sazerac."},

    # Mixers / juices / syrups
    {"name": "Lime Juice", "category": "juice", "abv": 0, "flavor_profile": ["citrus", "tart", "bright"], "notes": "Fresh only. Oxidises within hours."},
    {"name": "Lemon Juice", "category": "juice", "abv": 0, "flavor_profile": ["citrus", "tart", "fresh"], "notes": "Fresh only."},
    {"name": "Orange Juice", "category": "juice", "abv": 0, "flavor_profile": ["citrus", "sweet"], "notes": "Fresh for service."},
    {"name": "Grapefruit Juice", "category": "juice", "abv": 0, "flavor_profile": ["citrus", "bitter", "tart"], "notes": "Paloma."},
    {"name": "Pineapple Juice", "category": "juice", "abv": 0, "flavor_profile": ["tropical", "sweet", "tart"], "notes": "Shakes to a froth — pineapple-syrup foam."},
    {"name": "Cranberry Juice", "category": "juice", "abv": 0, "flavor_profile": ["tart", "fruit"], "notes": "Cosmo, Cape Codder."},
    {"name": "Simple Syrup (1:1)", "category": "syrup", "abv": 0, "flavor_profile": ["sweet"], "notes": "Equal parts sugar/water."},
    {"name": "Rich Simple (2:1)", "category": "syrup", "abv": 0, "flavor_profile": ["sweet", "thick"], "notes": "2:1 sugar:water. Old Fashioned weapon of choice."},
    {"name": "Demerara Syrup", "category": "syrup", "abv": 0, "flavor_profile": ["sweet", "molasses", "caramel"], "notes": "Tiki, aged rum drinks."},
    {"name": "Honey Syrup", "category": "syrup", "abv": 0, "flavor_profile": ["floral", "sweet"], "notes": "3:1 honey:water. Bee's Knees, Penicillin."},
    {"name": "Agave Syrup", "category": "syrup", "abv": 0, "flavor_profile": ["sweet", "vegetal"], "notes": "Pairs with tequila/mezcal."},
    {"name": "Grenadine (real)", "category": "syrup", "abv": 0, "flavor_profile": ["pomegranate", "sweet"], "notes": "Real is pomegranate, not red dye."},
    {"name": "Orgeat", "category": "syrup", "abv": 0, "flavor_profile": ["almond", "nutty", "sweet", "floral"], "notes": "Mai Tai, Japanese Cocktail."},
    {"name": "Egg White", "category": "modifier", "abv": 0, "flavor_profile": ["neutral"], "notes": "Silky texture, foam. Dry shake first!"},
    {"name": "Heavy Cream", "category": "dairy", "abv": 0, "flavor_profile": ["cream", "rich"], "notes": "WILL CURDLE with citrus/acidic wines."},
    {"name": "Coconut Cream", "category": "dairy alt", "abv": 0, "flavor_profile": ["tropical", "creamy", "sweet"], "notes": "Piña Colada."},
    {"name": "Soda Water", "category": "mixer", "abv": 0, "flavor_profile": ["neutral", "fizz"], "notes": "Length, lift, dilution."},
    {"name": "Tonic Water", "category": "mixer", "abv": 0, "flavor_profile": ["bitter", "quinine", "sweet"], "notes": "G&T. Quinine can clash with cream."},
    {"name": "Ginger Beer", "category": "mixer", "abv": 0, "flavor_profile": ["spicy", "ginger", "sweet"], "notes": "Mules, Dark & Stormy."},
    {"name": "Champagne / Prosecco", "category": "wine", "abv": 12, "flavor_profile": ["fizzy", "dry", "yeasty"], "notes": "French 75, Spritz, Mimosa."},
]

# Clash / compatibility rules
CLASH_RULES = [
    {"a": "Baileys Irish Cream", "b": "Lime Juice", "severity": "fatal", "reason": "Dairy cream curdles immediately on contact with citric acid — turns lumpy and inedible."},
    {"a": "Baileys Irish Cream", "b": "Lemon Juice", "severity": "fatal", "reason": "Same as lime — citric acid curdles the cream."},
    {"a": "Baileys Irish Cream", "b": "Grapefruit Juice", "severity": "fatal", "reason": "Citric acid → curdles."},
    {"a": "Baileys Irish Cream", "b": "Tonic Water", "severity": "high", "reason": "Quinine + dairy = curdling and a chalky mouthfeel."},
    {"a": "Baileys Irish Cream", "b": "Champagne / Prosecco", "severity": "high", "reason": "Acidic wine + dairy curdles."},
    {"a": "Heavy Cream", "b": "Lime Juice", "severity": "fatal", "reason": "Acid + cream = curdle. Use coconut cream instead for tropical creamy citrus."},
    {"a": "Heavy Cream", "b": "Lemon Juice", "severity": "fatal", "reason": "Same — curdles."},
    {"a": "Heavy Cream", "b": "Champagne / Prosecco", "severity": "high", "reason": "Acidic sparkling wine curdles cream."},
    {"a": "Pernod / Absinthe", "b": "Cream", "severity": "medium", "reason": "Anise-louche can muddy a creamy drink. Use sparingly."},
    {"a": "Campari", "b": "Heavy Cream", "severity": "medium", "reason": "Bitter + cream is rarely pleasant. Doable but tricky."},
    {"a": "Mezcal", "b": "Crème de Cacao", "severity": "low", "reason": "Smoke vs chocolate can clash if proportions are off. Possible but careful."},
    {"a": "Tequila Blanco", "b": "Coffee Liqueur (Kahlúa)", "severity": "low", "reason": "Vegetal agave vs sweet coffee — unusual pairing, balance carefully."},
    {"a": "Fernet-Branca", "b": "Sweet liqueurs", "severity": "low", "reason": "Fernet's intense bitterness fights most sweet liqueurs. Use in small accents."},
    {"a": "London Dry Gin", "b": "Coffee Liqueur (Kahlúa)", "severity": "medium", "reason": "Pine/juniper vs coffee is a strange flavour battle."},
]

# Classic cocktail recipes
COCKTAILS = [
    {
        "name": "Old Fashioned",
        "category": "spirit-forward",
        "glassware": "Rocks",
        "garnish": "Orange peel (express oils)",
        "method": "Build & stir",
        "ingredients": [
            {"name": "Bourbon", "amount_ml": 60, "notes": "or Rye"},
            {"name": "Rich Simple (2:1)", "amount_ml": 5},
            {"name": "Angostura Bitters", "amount_ml": 1.5, "notes": "2-3 dashes"},
        ],
        "instructions": "Add all to mixing glass with ice. Stir 30s until well diluted. Strain over large rock. Express orange peel over and drop in.",
        "flavor_profile": ["sweet", "bitter", "warm", "spirit-forward"],
        "abv_estimate": 32,
        "tags": ["classic", "IBA", "stirred"],
    },
    {
        "name": "Manhattan",
        "category": "spirit-forward",
        "glassware": "Coupe",
        "garnish": "Brandied cherry",
        "method": "Stir",
        "ingredients": [
            {"name": "Rye Whiskey", "amount_ml": 60},
            {"name": "Sweet Vermouth", "amount_ml": 30},
            {"name": "Angostura Bitters", "amount_ml": 1.5, "notes": "2 dashes"},
        ],
        "instructions": "Stir over ice 30s. Strain into chilled coupe. Cherry garnish.",
        "flavor_profile": ["sweet", "spicy", "herbal", "spirit-forward"],
        "abv_estimate": 28,
        "tags": ["classic", "IBA", "stirred"],
    },
    {
        "name": "Negroni",
        "category": "bitter",
        "glassware": "Rocks",
        "garnish": "Orange wheel or peel",
        "method": "Build & stir",
        "ingredients": [
            {"name": "London Dry Gin", "amount_ml": 30},
            {"name": "Campari", "amount_ml": 30},
            {"name": "Sweet Vermouth", "amount_ml": 30},
        ],
        "instructions": "Build over ice in rocks glass. Stir briefly. Orange peel.",
        "flavor_profile": ["bitter", "herbal", "orange"],
        "abv_estimate": 24,
        "tags": ["classic", "IBA", "equal-parts"],
    },
    {
        "name": "Boulevardier",
        "category": "bitter",
        "glassware": "Rocks or coupe",
        "garnish": "Orange peel",
        "method": "Stir",
        "ingredients": [
            {"name": "Bourbon", "amount_ml": 45},
            {"name": "Campari", "amount_ml": 30},
            {"name": "Sweet Vermouth", "amount_ml": 30},
        ],
        "instructions": "Stir over ice. Strain over fresh rock or up. Orange peel.",
        "flavor_profile": ["bitter", "sweet", "warm"],
        "abv_estimate": 26,
        "tags": ["classic", "stirred"],
    },
    {
        "name": "Margarita",
        "category": "sour",
        "glassware": "Coupe or rocks",
        "garnish": "Half salt rim, lime wheel",
        "method": "Shake",
        "ingredients": [
            {"name": "Tequila Blanco", "amount_ml": 50},
            {"name": "Cointreau", "amount_ml": 20},
            {"name": "Lime Juice", "amount_ml": 25},
        ],
        "instructions": "Shake hard with ice 12s. Double strain. Optional half salt rim.",
        "flavor_profile": ["citrus", "agave", "sweet", "tart"],
        "abv_estimate": 22,
        "tags": ["classic", "IBA", "shaken", "citrus"],
    },
    {
        "name": "Tommy's Margarita",
        "category": "sour",
        "glassware": "Rocks",
        "garnish": "Lime wheel",
        "method": "Shake",
        "ingredients": [
            {"name": "Tequila Blanco", "amount_ml": 60},
            {"name": "Lime Juice", "amount_ml": 25},
            {"name": "Agave Syrup", "amount_ml": 15},
        ],
        "instructions": "Shake hard. Strain over fresh ice.",
        "flavor_profile": ["citrus", "agave", "clean"],
        "abv_estimate": 22,
        "tags": ["modern classic"],
    },
    {
        "name": "Daiquiri",
        "category": "sour",
        "glassware": "Coupe",
        "garnish": "Lime wheel",
        "method": "Shake",
        "ingredients": [
            {"name": "White Rum", "amount_ml": 60},
            {"name": "Lime Juice", "amount_ml": 25},
            {"name": "Simple Syrup (1:1)", "amount_ml": 15},
        ],
        "instructions": "Shake hard, double strain into chilled coupe.",
        "flavor_profile": ["citrus", "sweet", "clean"],
        "abv_estimate": 22,
        "tags": ["classic", "IBA", "shaken", "citrus"],
    },
    {
        "name": "Whiskey Sour",
        "category": "sour",
        "glassware": "Coupe or rocks",
        "garnish": "Cherry, optional orange",
        "method": "Shake (dry shake if using egg white)",
        "ingredients": [
            {"name": "Bourbon", "amount_ml": 60},
            {"name": "Lemon Juice", "amount_ml": 25},
            {"name": "Simple Syrup (1:1)", "amount_ml": 20},
            {"name": "Egg White", "amount_ml": 15, "notes": "optional"},
        ],
        "instructions": "Dry shake (no ice) 15s if using egg white, then shake with ice. Strain.",
        "flavor_profile": ["sweet", "sour", "warm"],
        "abv_estimate": 18,
        "tags": ["classic", "IBA"],
    },
    {
        "name": "Espresso Martini",
        "category": "after-dinner",
        "glassware": "Coupe",
        "garnish": "3 coffee beans",
        "method": "Shake (hard)",
        "ingredients": [
            {"name": "Vodka", "amount_ml": 50},
            {"name": "Coffee Liqueur (Kahlúa)", "amount_ml": 20},
            {"name": "Simple Syrup (1:1)", "amount_ml": 10},
            {"name": "Espresso", "amount_ml": 30, "notes": "fresh, hot or cold-brew concentrate"},
        ],
        "instructions": "Shake VERY hard with ice for that crema-like foam. Double strain. Three beans on top.",
        "flavor_profile": ["coffee", "sweet", "rich"],
        "abv_estimate": 22,
        "tags": ["modern classic", "shaken"],
    },
    {
        "name": "Mojito",
        "category": "highball",
        "glassware": "Highball",
        "garnish": "Mint sprig, lime wedge",
        "method": "Build",
        "ingredients": [
            {"name": "White Rum", "amount_ml": 50},
            {"name": "Lime Juice", "amount_ml": 25},
            {"name": "Simple Syrup (1:1)", "amount_ml": 15},
            {"name": "Mint leaves", "amount_ml": 0, "notes": "8-10 leaves, gently slapped (NOT muddled to mush)"},
            {"name": "Soda Water", "amount_ml": 60, "notes": "top"},
        ],
        "instructions": "Gently press mint (don't shred it). Add rum, lime, syrup, ice. Top soda. Stir lightly.",
        "flavor_profile": ["mint", "citrus", "refreshing"],
        "abv_estimate": 12,
        "tags": ["classic", "IBA", "long"],
    },
    {
        "name": "Aperol Spritz",
        "category": "aperitivo",
        "glassware": "Wine glass",
        "garnish": "Orange slice",
        "method": "Build",
        "ingredients": [
            {"name": "Aperol", "amount_ml": 60},
            {"name": "Champagne / Prosecco", "amount_ml": 90},
            {"name": "Soda Water", "amount_ml": 30, "notes": "splash"},
        ],
        "instructions": "Fill wine glass with ice. Prosecco first (preserves bubbles), then Aperol, splash soda. Orange.",
        "flavor_profile": ["bitter", "orange", "fizzy", "light"],
        "abv_estimate": 11,
        "tags": ["classic", "IBA", "low-abv", "aperitif"],
    },
    {
        "name": "Penicillin",
        "category": "sour",
        "glassware": "Rocks",
        "garnish": "Candied ginger, optional peated float",
        "method": "Shake + float",
        "ingredients": [
            {"name": "Scotch (Blended)", "amount_ml": 60},
            {"name": "Lemon Juice", "amount_ml": 22.5},
            {"name": "Honey Syrup", "amount_ml": 22.5, "notes": "ginger-infused honey is the move"},
            {"name": "Scotch (Islay/Peated)", "amount_ml": 7.5, "notes": "float on top"},
        ],
        "instructions": "Shake first three with ice. Strain over fresh rock. Gently float peated scotch via spoon.",
        "flavor_profile": ["smoky", "honey", "ginger", "citrus"],
        "abv_estimate": 22,
        "tags": ["modern classic"],
    },
    {
        "name": "Paper Plane",
        "category": "sour",
        "glassware": "Coupe",
        "garnish": "None (or paper plane)",
        "method": "Shake",
        "ingredients": [
            {"name": "Bourbon", "amount_ml": 22.5},
            {"name": "Aperol", "amount_ml": 22.5},
            {"name": "Amaro Nonino", "amount_ml": 22.5, "notes": "or another medium-bitter amaro"},
            {"name": "Lemon Juice", "amount_ml": 22.5},
        ],
        "instructions": "Equal parts shake. Double strain.",
        "flavor_profile": ["bitter", "citrus", "herbal"],
        "abv_estimate": 18,
        "tags": ["modern classic", "equal-parts"],
    },
    {
        "name": "French 75",
        "category": "champagne",
        "glassware": "Flute",
        "garnish": "Lemon twist",
        "method": "Shake + top",
        "ingredients": [
            {"name": "London Dry Gin", "amount_ml": 30},
            {"name": "Lemon Juice", "amount_ml": 15},
            {"name": "Simple Syrup (1:1)", "amount_ml": 10},
            {"name": "Champagne / Prosecco", "amount_ml": 60, "notes": "top"},
        ],
        "instructions": "Shake first three. Strain into flute. Top with bubbles. Lemon twist.",
        "flavor_profile": ["citrus", "dry", "fizzy"],
        "abv_estimate": 16,
        "tags": ["classic", "IBA"],
    },
    {
        "name": "Last Word",
        "category": "sour",
        "glassware": "Coupe",
        "garnish": "Brandied cherry",
        "method": "Shake",
        "ingredients": [
            {"name": "London Dry Gin", "amount_ml": 22.5},
            {"name": "Green Chartreuse", "amount_ml": 22.5},
            {"name": "Maraschino", "amount_ml": 22.5},
            {"name": "Lime Juice", "amount_ml": 22.5},
        ],
        "instructions": "Shake equal parts. Double strain.",
        "flavor_profile": ["herbal", "citrus", "complex"],
        "abv_estimate": 24,
        "tags": ["classic", "equal-parts"],
    },
    {
        "name": "Aviation",
        "category": "sour",
        "glassware": "Coupe",
        "garnish": "Brandied cherry",
        "method": "Shake",
        "ingredients": [
            {"name": "London Dry Gin", "amount_ml": 45},
            {"name": "Maraschino", "amount_ml": 15},
            {"name": "Crème de Violette", "amount_ml": 7.5},
            {"name": "Lemon Juice", "amount_ml": 22.5},
        ],
        "instructions": "Shake. Double strain. Pale violet hue.",
        "flavor_profile": ["floral", "citrus", "complex"],
        "abv_estimate": 22,
        "tags": ["classic", "IBA"],
    },
    {
        "name": "Cosmopolitan",
        "category": "sour",
        "glassware": "Coupe",
        "garnish": "Lime wheel or flamed orange",
        "method": "Shake",
        "ingredients": [
            {"name": "Citrus Vodka", "amount_ml": 45, "notes": "or plain vodka"},
            {"name": "Cointreau", "amount_ml": 15},
            {"name": "Lime Juice", "amount_ml": 15},
            {"name": "Cranberry Juice", "amount_ml": 30},
        ],
        "instructions": "Shake hard. Double strain.",
        "flavor_profile": ["tart", "fruity", "citrus"],
        "abv_estimate": 22,
        "tags": ["classic", "IBA"],
    },
    {
        "name": "Gimlet",
        "category": "sour",
        "glassware": "Coupe",
        "garnish": "Lime wheel",
        "method": "Shake",
        "ingredients": [
            {"name": "London Dry Gin", "amount_ml": 60},
            {"name": "Lime Juice", "amount_ml": 22.5},
            {"name": "Simple Syrup (1:1)", "amount_ml": 15},
        ],
        "instructions": "Shake. Strain into coupe.",
        "flavor_profile": ["citrus", "herbal", "dry"],
        "abv_estimate": 24,
        "tags": ["classic"],
    },
    {
        "name": "Sazerac",
        "category": "spirit-forward",
        "glassware": "Rocks (chilled, no ice)",
        "garnish": "Lemon peel (express, discard)",
        "method": "Stir + rinse",
        "ingredients": [
            {"name": "Rye Whiskey", "amount_ml": 60, "notes": "or cognac"},
            {"name": "Pernod / Absinthe", "amount_ml": 5, "notes": "RINSE — discard excess"},
            {"name": "Demerara Syrup", "amount_ml": 5},
            {"name": "Peychaud's Bitters", "amount_ml": 1.5, "notes": "3 dashes"},
        ],
        "instructions": "Rinse chilled rocks glass with absinthe (discard). Stir rye, syrup, bitters over ice. Strain into prepared glass (no ice). Lemon peel, discard.",
        "flavor_profile": ["spicy", "anise", "complex", "spirit-forward"],
        "abv_estimate": 38,
        "tags": ["classic", "IBA", "stirred"],
    },
    {
        "name": "Vesper",
        "category": "spirit-forward",
        "glassware": "Coupe",
        "garnish": "Lemon peel",
        "method": "Shake (per Bond) or stir",
        "ingredients": [
            {"name": "London Dry Gin", "amount_ml": 60},
            {"name": "Vodka", "amount_ml": 20},
            {"name": "Lillet Blanc", "amount_ml": 10},
        ],
        "instructions": "Shake or stir until very cold. Strain into chilled coupe. Lemon peel.",
        "flavor_profile": ["dry", "clean", "spirit-forward"],
        "abv_estimate": 32,
        "tags": ["classic", "IBA"],
    },
    {
        "name": "Dark & Stormy",
        "category": "highball",
        "glassware": "Highball",
        "garnish": "Lime wedge",
        "method": "Build",
        "ingredients": [
            {"name": "Dark Rum", "amount_ml": 60, "notes": "Gosling's traditionally"},
            {"name": "Ginger Beer", "amount_ml": 120},
            {"name": "Lime Juice", "amount_ml": 15, "notes": "optional"},
        ],
        "instructions": "Build over ice in highball. Float rum over ginger beer for the 'stormy' look.",
        "flavor_profile": ["spicy", "molasses", "citrus"],
        "abv_estimate": 11,
        "tags": ["classic", "long"],
    },
    {
        "name": "Bramble",
        "category": "sour",
        "glassware": "Rocks (crushed ice)",
        "garnish": "Blackberry, lemon wedge",
        "method": "Build + drizzle",
        "ingredients": [
            {"name": "London Dry Gin", "amount_ml": 50},
            {"name": "Lemon Juice", "amount_ml": 25},
            {"name": "Simple Syrup (1:1)", "amount_ml": 12.5},
            {"name": "Crème de Mûre", "amount_ml": 15, "notes": "drizzle"},
        ],
        "instructions": "Shake first three. Strain over crushed ice. Drizzle mûre over the top for that bleeding-in look.",
        "flavor_profile": ["citrus", "berry", "fruity"],
        "abv_estimate": 18,
        "tags": ["modern classic", "IBA"],
    },
    # ───────────── Phase 2 additions ─────────────
    {
        "name": "Mai Tai",
        "category": "tiki",
        "glassware": "Double rocks (crushed ice)",
        "garnish": "Spent lime shell + mint sprig",
        "method": "Shake",
        "ingredients": [
            {"name": "Aged Rum", "amount_ml": 30, "notes": "Jamaican preferred"},
            {"name": "Aged Rum", "amount_ml": 30, "notes": "Martinique/agricole — split base"},
            {"name": "Orange Curaçao", "amount_ml": 15},
            {"name": "Lime Juice", "amount_ml": 25},
            {"name": "Orgeat", "amount_ml": 12},
            {"name": "Rich Simple (2:1)", "amount_ml": 5},
        ],
        "instructions": "Shake briefly with crushed ice. Dump into glass. Cap with more crushed ice. Spent lime + mint.",
        "flavor_profile": ["tropical", "citrus", "nutty", "warm"],
        "abv_estimate": 24,
        "tags": ["classic", "tiki"],
    },
    {
        "name": "Jungle Bird",
        "category": "tiki",
        "glassware": "Rocks",
        "garnish": "Pineapple frond",
        "method": "Shake",
        "ingredients": [
            {"name": "Aged Rum", "amount_ml": 45, "notes": "blackstrap-leaning"},
            {"name": "Campari", "amount_ml": 22.5},
            {"name": "Pineapple Juice", "amount_ml": 45},
            {"name": "Lime Juice", "amount_ml": 15},
            {"name": "Demerara Syrup", "amount_ml": 15},
        ],
        "instructions": "Shake hard. Strain over fresh ice.",
        "flavor_profile": ["bitter", "tropical", "tart"],
        "abv_estimate": 18,
        "tags": ["modern classic", "tiki"],
    },
    {
        "name": "Piña Colada",
        "category": "tiki",
        "glassware": "Hurricane / coupe",
        "garnish": "Pineapple wedge",
        "method": "Blend or shake hard",
        "ingredients": [
            {"name": "White Rum", "amount_ml": 60},
            {"name": "Coconut Cream", "amount_ml": 30},
            {"name": "Pineapple Juice", "amount_ml": 90},
            {"name": "Lime Juice", "amount_ml": 7.5, "notes": "optional, balances sweetness"},
        ],
        "instructions": "Blend with crushed ice till smooth. Or hard-shake over ice and strain over crushed.",
        "flavor_profile": ["tropical", "creamy", "sweet"],
        "abv_estimate": 12,
        "tags": ["classic", "IBA", "tiki"],
    },
    {
        "name": "Hemingway Daiquiri",
        "category": "sour",
        "glassware": "Coupe",
        "garnish": "Lime wheel",
        "method": "Shake",
        "ingredients": [
            {"name": "White Rum", "amount_ml": 60, "notes": "or aged"},
            {"name": "Lime Juice", "amount_ml": 22.5},
            {"name": "Grapefruit Juice", "amount_ml": 15},
            {"name": "Maraschino", "amount_ml": 7.5},
        ],
        "instructions": "Shake hard, double strain. Sugarless — only sweetness is maraschino.",
        "flavor_profile": ["citrus", "tart", "complex"],
        "abv_estimate": 22,
        "tags": ["classic"],
    },
    {
        "name": "Bee's Knees",
        "category": "sour",
        "glassware": "Coupe",
        "garnish": "Lemon twist",
        "method": "Shake",
        "ingredients": [
            {"name": "London Dry Gin", "amount_ml": 60},
            {"name": "Honey Syrup", "amount_ml": 22.5, "notes": "3:1 honey:hot water"},
            {"name": "Lemon Juice", "amount_ml": 22.5},
        ],
        "instructions": "Shake hard till honey fully integrates. Double strain.",
        "flavor_profile": ["honey", "citrus", "floral"],
        "abv_estimate": 22,
        "tags": ["prohibition", "classic"],
    },
    {
        "name": "Naked & Famous",
        "category": "sour",
        "glassware": "Coupe",
        "garnish": "None",
        "method": "Shake",
        "ingredients": [
            {"name": "Mezcal", "amount_ml": 22.5},
            {"name": "Yellow Chartreuse", "amount_ml": 22.5},
            {"name": "Aperol", "amount_ml": 22.5},
            {"name": "Lime Juice", "amount_ml": 22.5},
        ],
        "instructions": "Equal parts shake. Double strain.",
        "flavor_profile": ["smoky", "bitter", "citrus", "herbal"],
        "abv_estimate": 22,
        "tags": ["modern classic", "equal-parts"],
    },
    {
        "name": "Oaxaca Old Fashioned",
        "category": "spirit-forward",
        "glassware": "Rocks",
        "garnish": "Flamed orange peel",
        "method": "Stir",
        "ingredients": [
            {"name": "Tequila Reposado", "amount_ml": 45},
            {"name": "Mezcal", "amount_ml": 15},
            {"name": "Agave Syrup", "amount_ml": 5},
            {"name": "Angostura Bitters", "amount_ml": 1.5, "notes": "2 dashes"},
        ],
        "instructions": "Stir over ice. Strain over big rock. Flame orange peel for that drama.",
        "flavor_profile": ["smoky", "agave", "warm", "spirit-forward"],
        "abv_estimate": 32,
        "tags": ["modern classic", "stirred"],
    },
    {
        "name": "Sidecar",
        "category": "sour",
        "glassware": "Coupe (optional sugar rim)",
        "garnish": "Orange twist",
        "method": "Shake",
        "ingredients": [
            {"name": "Cognac VS", "amount_ml": 50},
            {"name": "Cointreau", "amount_ml": 20},
            {"name": "Lemon Juice", "amount_ml": 20},
        ],
        "instructions": "Shake hard, double strain. Half-rim with caster sugar if you fancy.",
        "flavor_profile": ["citrus", "warm", "fruit"],
        "abv_estimate": 26,
        "tags": ["classic", "IBA"],
    },
    {
        "name": "Vieux Carré",
        "category": "spirit-forward",
        "glassware": "Rocks",
        "garnish": "Lemon twist",
        "method": "Stir",
        "ingredients": [
            {"name": "Rye Whiskey", "amount_ml": 22.5},
            {"name": "Cognac VS", "amount_ml": 22.5},
            {"name": "Sweet Vermouth", "amount_ml": 22.5},
            {"name": "Benedictine", "amount_ml": 5},
            {"name": "Peychaud's Bitters", "amount_ml": 1, "notes": "2 dashes"},
            {"name": "Angostura Bitters", "amount_ml": 1, "notes": "2 dashes"},
        ],
        "instructions": "Stir over ice. Strain over fresh ice. Lemon twist.",
        "flavor_profile": ["complex", "herbal", "spice", "warm"],
        "abv_estimate": 28,
        "tags": ["classic", "stirred"],
    },
    {
        "name": "Tom Collins",
        "category": "highball",
        "glassware": "Highball / Collins",
        "garnish": "Lemon wheel, cherry",
        "method": "Build (shake juice first)",
        "ingredients": [
            {"name": "Old Tom Gin", "amount_ml": 50, "notes": "or London Dry"},
            {"name": "Lemon Juice", "amount_ml": 25},
            {"name": "Simple Syrup (1:1)", "amount_ml": 15},
            {"name": "Soda Water", "amount_ml": 60, "notes": "top"},
        ],
        "instructions": "Shake gin, lemon, syrup with ice. Strain into iced Collins glass. Top with soda. Stir once.",
        "flavor_profile": ["citrus", "refreshing", "fizzy"],
        "abv_estimate": 12,
        "tags": ["classic", "IBA", "long"],
    },
    {
        "name": "Moscow Mule",
        "category": "highball",
        "glassware": "Copper mug",
        "garnish": "Lime wedge, mint",
        "method": "Build",
        "ingredients": [
            {"name": "Vodka", "amount_ml": 50},
            {"name": "Lime Juice", "amount_ml": 15},
            {"name": "Ginger Beer", "amount_ml": 120, "notes": "top"},
        ],
        "instructions": "Build over ice in copper mug. Top with ginger beer. Stir gently.",
        "flavor_profile": ["spicy", "citrus", "refreshing"],
        "abv_estimate": 10,
        "tags": ["classic", "long"],
    },
    {
        "name": "Mint Julep",
        "category": "highball",
        "glassware": "Julep cup (crushed ice mountain)",
        "garnish": "Mint bouquet",
        "method": "Muddle gently + swizzle",
        "ingredients": [
            {"name": "Bourbon", "amount_ml": 75},
            {"name": "Simple Syrup (1:1)", "amount_ml": 10},
            {"name": "Mint Leaves", "amount_ml": 0, "notes": "8-10 leaves, gently press"},
        ],
        "instructions": "Press mint with syrup in julep cup. Add bourbon. Pack with crushed ice. Swizzle. Cap with more crushed ice + giant mint bouquet aimed at the nose.",
        "flavor_profile": ["mint", "warm", "refreshing"],
        "abv_estimate": 26,
        "tags": ["classic", "IBA"],
    },
    {
        "name": "Americano",
        "category": "aperitivo",
        "glassware": "Highball or rocks",
        "garnish": "Orange slice, lemon twist",
        "method": "Build",
        "ingredients": [
            {"name": "Campari", "amount_ml": 30},
            {"name": "Sweet Vermouth", "amount_ml": 30},
            {"name": "Soda Water", "amount_ml": 60, "notes": "top"},
        ],
        "instructions": "Build over ice. Top with soda. Stir once.",
        "flavor_profile": ["bitter", "orange", "light", "fizzy"],
        "abv_estimate": 8,
        "tags": ["classic", "IBA", "low-abv", "aperitif"],
    },
    {
        "name": "Hugo Spritz",
        "category": "aperitivo",
        "glassware": "Wine glass",
        "garnish": "Mint sprig, lime wheel",
        "method": "Build",
        "ingredients": [
            {"name": "St-Germain (Elderflower)", "amount_ml": 45},
            {"name": "Champagne / Prosecco", "amount_ml": 90},
            {"name": "Soda Water", "amount_ml": 30, "notes": "splash"},
            {"name": "Mint Leaves", "amount_ml": 0, "notes": "few, slapped"},
        ],
        "instructions": "Fill wine glass with ice. Mint + St-Germain. Top with Prosecco. Splash soda. Mint + lime.",
        "flavor_profile": ["floral", "fizzy", "light"],
        "abv_estimate": 9,
        "tags": ["modern classic", "low-abv", "aperitif"],
    },
    {
        "name": "Garibaldi",
        "category": "aperitivo",
        "glassware": "Highball",
        "garnish": "Orange wheel",
        "method": "Build (fluff the juice)",
        "ingredients": [
            {"name": "Campari", "amount_ml": 45},
            {"name": "Orange Juice", "amount_ml": 120, "notes": "FRESH and ideally high-speed blended for foam"},
        ],
        "instructions": "Aerate fresh OJ in a high-speed blender 5s till frothy. Pour Campari over ice. Top with fluffy OJ.",
        "flavor_profile": ["bitter", "orange", "refreshing"],
        "abv_estimate": 8,
        "tags": ["modern classic", "low-abv", "aperitif"],
    },
    {
        "name": "Pisco Sour",
        "category": "sour",
        "glassware": "Coupe",
        "garnish": "3 dashes Angostura on foam",
        "method": "Dry shake then wet shake",
        "ingredients": [
            {"name": "Pisco", "amount_ml": 60},
            {"name": "Lemon Juice", "amount_ml": 25, "notes": "or lime in Peru"},
            {"name": "Simple Syrup (1:1)", "amount_ml": 20},
            {"name": "Egg White", "amount_ml": 15},
            {"name": "Angostura Bitters", "amount_ml": 1, "notes": "2-3 dashes on foam after pouring"},
        ],
        "instructions": "Dry shake (no ice) 15s. Add ice, shake again. Double strain. Dot bitters on foam, draw a pattern.",
        "flavor_profile": ["citrus", "creamy", "floral"],
        "abv_estimate": 18,
        "tags": ["classic", "IBA"],
    },
    {
        "name": "Caipirinha",
        "category": "sour",
        "glassware": "Rocks",
        "garnish": "Lime wheel",
        "method": "Muddle + build",
        "ingredients": [
            {"name": "Cachaça", "amount_ml": 60},
            {"name": "Lime", "amount_ml": 0, "notes": "1 whole lime, cut in wedges"},
            {"name": "Caster Sugar", "amount_ml": 0, "notes": "2 bar spoons (10g)"},
        ],
        "instructions": "Muddle lime wedges with sugar in glass. Add cachaça. Fill with crushed ice. Churn to mix.",
        "flavor_profile": ["citrus", "grassy", "fresh"],
        "abv_estimate": 26,
        "tags": ["classic", "IBA"],
    },
    {
        "name": "Hanky Panky",
        "category": "spirit-forward",
        "glassware": "Coupe",
        "garnish": "Flamed orange peel",
        "method": "Stir",
        "ingredients": [
            {"name": "London Dry Gin", "amount_ml": 45},
            {"name": "Sweet Vermouth", "amount_ml": 45},
            {"name": "Fernet-Branca", "amount_ml": 7.5},
        ],
        "instructions": "Stir over ice. Strain. Express flamed orange peel.",
        "flavor_profile": ["bitter", "herbal", "spirit-forward"],
        "abv_estimate": 28,
        "tags": ["classic", "stirred"],
    },
    {
        "name": "Corpse Reviver #2",
        "category": "sour",
        "glassware": "Coupe (absinthe rinsed)",
        "garnish": "Lemon twist",
        "method": "Shake",
        "ingredients": [
            {"name": "London Dry Gin", "amount_ml": 22.5},
            {"name": "Cointreau", "amount_ml": 22.5},
            {"name": "Lillet Blanc", "amount_ml": 22.5, "notes": "or Cocchi Americano (closer to original Kina Lillet)"},
            {"name": "Lemon Juice", "amount_ml": 22.5},
            {"name": "Pernod / Absinthe", "amount_ml": 2, "notes": "RINSE the coupe, discard"},
        ],
        "instructions": "Rinse chilled coupe with absinthe. Equal parts shake the rest. Double strain into rinsed coupe.",
        "flavor_profile": ["citrus", "herbal", "anise", "complex"],
        "abv_estimate": 22,
        "tags": ["classic", "equal-parts"],
    },
    {
        "name": "White Russian",
        "category": "after-dinner",
        "glassware": "Rocks",
        "garnish": "None",
        "method": "Build + float",
        "ingredients": [
            {"name": "Vodka", "amount_ml": 50},
            {"name": "Coffee Liqueur (Kahlúa)", "amount_ml": 20},
            {"name": "Heavy Cream", "amount_ml": 30, "notes": "float gently"},
        ],
        "instructions": "Build vodka + coffee liqueur over ice. Float cream over a spoon. Stir before drinking if you don't want layers.",
        "flavor_profile": ["creamy", "coffee", "sweet"],
        "abv_estimate": 18,
        "tags": ["classic", "IBA"],
    },
    {
        "name": "Paloma",
        "category": "highball",
        "glassware": "Highball (salt rim optional)",
        "garnish": "Lime wedge",
        "method": "Build",
        "ingredients": [
            {"name": "Tequila Blanco", "amount_ml": 50},
            {"name": "Lime Juice", "amount_ml": 15},
            {"name": "Grapefruit Soda", "amount_ml": 120, "notes": "or 60ml grapefruit juice + 60ml soda + agave"},
        ],
        "instructions": "Build over ice in highball. Stir once. Half salt rim if you like.",
        "flavor_profile": ["citrus", "bitter", "refreshing"],
        "abv_estimate": 10,
        "tags": ["classic", "long"],
    },
]


# ───────────── Substitutions ─────────────
# When an ingredient is 86'd or you want flexibility, here's the bartender's playbook.
SUBSTITUTIONS = [
    {
        "ingredient": "Cointreau",
        "subs": [
            {"name": "Grand Marnier", "notes": "Adds cognac depth; slightly heavier. 1:1."},
            {"name": "Triple Sec", "notes": "Cheaper, less complex. Reduce sugar elsewhere or use 10% less."},
            {"name": "Orange Curaçao", "notes": "Pierre Ferrand or similar — coloured, slightly richer."},
        ],
    },
    {
        "ingredient": "Bourbon",
        "subs": [
            {"name": "Rye Whiskey", "notes": "Spicier, drier. Same proof. Manhattans love it."},
            {"name": "Irish Whiskey", "notes": "Lighter, smoother. Less vanilla/oak punch."},
            {"name": "Aged Rum", "notes": "Sweeter, tropical lean. Try in Old Fashioneds."},
        ],
    },
    {
        "ingredient": "Rye Whiskey",
        "subs": [
            {"name": "Bourbon", "notes": "Sweeter, less spicy. Manhattan goes softer."},
            {"name": "Scotch (Blended)", "notes": "Adds malt; works in Boulevardier variants."},
        ],
    },
    {
        "ingredient": "Lime Juice",
        "subs": [
            {"name": "Lemon Juice", "notes": "Brighter, less floral. Bump ~10% for matched sourness."},
            {"name": "Verjus", "notes": "Lower acid, gentler. Use 30% more."},
        ],
    },
    {
        "ingredient": "Lemon Juice",
        "subs": [
            {"name": "Lime Juice", "notes": "More tropical/floral. Reduce ~10%."},
            {"name": "Verjus", "notes": "Lower acid. Use 30% more."},
        ],
    },
    {
        "ingredient": "Sweet Vermouth",
        "subs": [
            {"name": "Punt e Mes", "notes": "Bitter sweet — Manhattan gains edge."},
            {"name": "Carpano Antica Formula", "notes": "Richer, vanilla-forward. Use slightly less."},
            {"name": "Cynar", "notes": "Lower ABV, vegetal-bitter. Different drink but stunning."},
        ],
    },
    {
        "ingredient": "Dry Vermouth",
        "subs": [
            {"name": "Lillet Blanc", "notes": "Sweeter, honeyed. Cut other sugar by half."},
            {"name": "Cocchi Americano", "notes": "Slightly bitter; close to vintage Kina Lillet."},
        ],
    },
    {
        "ingredient": "Campari",
        "subs": [
            {"name": "Aperol", "notes": "Half the bitter, half the ABV. Lighter spritz."},
            {"name": "Gran Classico", "notes": "Direct sub, drier finish, more herbal."},
            {"name": "Cynar", "notes": "Vegetal-bitter — Negroni gets darker, earthier."},
        ],
    },
    {
        "ingredient": "Aperol",
        "subs": [
            {"name": "Campari", "notes": "Double the bitter — drop quantity by 20% or add sugar."},
            {"name": "Suze", "notes": "Gentian bitter — drier, earthy."},
        ],
    },
    {
        "ingredient": "Maraschino",
        "subs": [
            {"name": "Kirsch", "notes": "Drier cherry; reduce sugar elsewhere."},
            {"name": "Crème de Cerise", "notes": "Sweeter, more fruit-forward."},
        ],
    },
    {
        "ingredient": "Green Chartreuse",
        "subs": [
            {"name": "Yellow Chartreuse", "notes": "Sweeter, less intense — use ~20% more."},
            {"name": "Genepy des Alpes", "notes": "Less complex but similar Alpine herbal kick."},
        ],
    },
    {
        "ingredient": "Yellow Chartreuse",
        "subs": [
            {"name": "Green Chartreuse", "notes": "Bigger ABV and intensity — use ~20% less."},
            {"name": "Strega", "notes": "Sweet herbal, saffron note. Different but works."},
        ],
    },
    {
        "ingredient": "Honey Syrup",
        "subs": [
            {"name": "Demerara Syrup", "notes": "Caramel instead of floral. Tiki-friendly."},
            {"name": "Maple Syrup (diluted 2:1)", "notes": "Earthier. Dilute with hot water first."},
            {"name": "Agave Syrup", "notes": "Vegetal — great with tequila/mezcal builds."},
        ],
    },
    {
        "ingredient": "Simple Syrup (1:1)",
        "subs": [
            {"name": "Rich Simple (2:1)", "notes": "Use about HALF the amount."},
            {"name": "Agave Syrup", "notes": "Tequila/mezcal builds."},
            {"name": "Demerara Syrup", "notes": "Adds molasses warmth."},
        ],
    },
    {
        "ingredient": "Egg White",
        "subs": [
            {"name": "Aquafaba", "notes": "Vegan. Same dry-shake. 22-30 ml."},
        ],
    },
    {
        "ingredient": "White Rum",
        "subs": [
            {"name": "Cachaça", "notes": "Grassier, funkier. Caipirinha lean."},
            {"name": "Pisco", "notes": "Floral, grape-based. Different but interesting."},
            {"name": "Tequila Blanco", "notes": "Vegetal — leans Margarita."},
        ],
    },
    {
        "ingredient": "Tequila Blanco",
        "subs": [
            {"name": "Mezcal", "notes": "Adds smoke. Try 50/50 split to ease into it."},
            {"name": "Pisco", "notes": "Less peppery, more grape."},
        ],
    },
    {
        "ingredient": "Mezcal",
        "subs": [
            {"name": "Tequila Blanco", "notes": "Loses smoke. Add a drop of liquid smoke or a smoked salt rim for similar effect."},
            {"name": "Peated Scotch", "notes": "Different smoke profile — works in Penicillin-adjacent drinks."},
        ],
    },
    {
        "ingredient": "Orgeat",
        "subs": [
            {"name": "Almond Syrup + Orange Flower Water", "notes": "DIY orgeat: almond syrup + a drop of OFW."},
            {"name": "Falernum", "notes": "Different but works in tiki — clove + lime + ginger."},
        ],
    },
    {
        "ingredient": "Cognac VS",
        "subs": [
            {"name": "Pisco", "notes": "Grape-based, lighter, floral."},
            {"name": "Aged Rum", "notes": "Caramel/oak; different fruit but same warmth."},
            {"name": "Brandy", "notes": "Direct sub if you've got it."},
        ],
    },
    {
        "ingredient": "Champagne / Prosecco",
        "subs": [
            {"name": "Cava", "notes": "Drier than Prosecco — closer to Champagne."},
            {"name": "Crémant", "notes": "French method, drier. Lovely in French 75."},
        ],
    },
    {
        "ingredient": "Lillet Blanc",
        "subs": [
            {"name": "Cocchi Americano", "notes": "Closer to original Kina Lillet — more bitter quinine."},
            {"name": "Dry Vermouth", "notes": "Drier and less honeyed; bump sugar in the build."},
        ],
    },
]
